spring:
  #profiles 선언하여 적용할 profile을 선택 한다.
  profiles: 
    active: local 
    
#  #DB 설정
#  datasource:
#    url: jdbc:log4jdbc:postgresql://192.168.0.200:5432/jhit_db
#    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    username: jhit_app
#    password: jhit1128!
    
    
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
#    static-path-pattern: /resources/**
    
  #JSP 바로적용 설정
  devtools:
    livereload:
      enabled: true
      
#내장 서버 포트
server.port: 8080

--- #local 환경 
spring: 
  profiles: local 
logging: 
  level: 
    root: error
    '[com.springboot]': debug